sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.8.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_install:
  - docker-compose up --build
  - ./bin/docker-run "mix local.rebar --force; mix local.hex --force; mix deps.get"

script:
  - ./mix/test-cover

after_script:
  - ./bin/docker-run "mix deps.get --only docs; MIX_ENV=docs mix inch.report"
  - docker-compose down

notifications:
  recipients:
    - dev@lone-cyprus.com
