version: '2'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  web:
    build: .
    image: raniemi/phoenix_examples 
    environment:
      MIX_ENV: dev
      MIX_HOME: /usr/local/src/phoenix_examples/.mix
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_NAME: phoenix_examples_dev
    command: bash -c "mix local.hex --force; mix local.rebar --force; mix do clean, deps.get, compile, ecto.create, phoenix.server"
    volumes:
      - .:/usr/local/src/phoenix_examples
    ports:
      - "4000:4000"
    links:
      - db
